FROM debian:latest

RUN apt-get update &&\
    apt-get -y install vim &&\
    apt-get -y install build-essential &&\
    apt-get -y install cmake &&\
    apt-get -y install clang &&\
    apt-get -y install gcc &&\
    apt-get -y install lldb &&\
    apt-get -y install gdb &&\
    apt-get -y install valgrind
