FROM alpine:latest

RUN apk update && apk upgrade \
    && apk add bash bash-doc bash-completion \
    && apk add vim \
    && apk add build-base git make cmake \
    && apk add clang lldb \
    && apk add gcc gdb \
    && apk add valgrind
