FROM ubuntu:latest

RUN apt-get update &&\
    apt-get -y install vim &&\
    apt-get -y install build-essential &&\
    apt-get -y install cmake &&\
	apt-get -y install clang gcc &&\
	apt-get -y install lldb gdb &&\
    apt-get -y install valgrind &&\
    apt-get -y install git &&\
	apt-get -y install libx11-dev
